package com.theironyard.novauc;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;


public class DataRepository<T> {
    private T t;
    private File file;
    private Scanner scannerFile;

    public DataRepository(String filename) throws IOException{
        file = new File(filename);
        scannerFile = new Scanner(file);
        scannerFile.useDelimiter("\n");
        //While this "Has tokens" use parse method of passed interface
        //parameter (FileObjectCreator) to make a person Object.
        //Store it in a hashmap with a key generated by ObjectKeyMapper

    }
    public void populateData(FileObjectCreator objectCreator, ObjectKeyMapper keyMapper) {
        while (scannerFile.hasNext()) {
            objectCreator.parse(scannerFile.next());
            keyMapper.map(P);
        }
    }


    public void set(T t){
        this.t = t;
    }
    public T get(){
        return t;
    }
    @FunctionalInterface
    interface FileObjectCreator<T>{ //
        T parse(String x);
    }
    @FunctionalInterface
    interface ObjectKeyMapper<T>{
        String map(T t);
    }
}
